# Generated by Django 2.2.14 on 2020-07-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200713_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='eartraininglevelpage',
            name='tab_title',
            field=models.CharField(default='Ear Training One', max_length=32),
            preserve_default=False,
        ),
    ]
