# Generated by Django 2.2.14 on 2020-07-23 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('main', '0005_eartraininglevelpage_tab_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='home_page_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
