# Generated by Django 2.2.14 on 2020-07-24 03:41

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_homepage_home_page_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eartrainingelementpage',
            name='body',
            field=wagtail.core.fields.StreamField([('topic', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('musical_elements', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('element_title', wagtail.core.blocks.CharBlock()), ('content', wagtail.core.blocks.StreamBlock([('rich_text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'li', 'hr', 'link', 'document_link'])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('music_example', wagtail.core.blocks.StructBlock([('file', wagtail.documents.blocks.DocumentChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('video', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock()), ('description', wagtail.core.blocks.CharBlock(required=False))]))], icon='cogs'))])))]))]),
        ),
    ]
