# Generated by Django 2.2.14 on 2020-07-24 04:56

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200724_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock()), ('image', wagtail.blocks.StructBlock([('image_file', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(help_text='Title for the image', required=False)), ('caption', wagtail.blocks.CharBlock(help_text='Caption for the image', required=False))]))]),
        ),
        migrations.AlterField(
            model_name='eartrainingelementpage',
            name='body',
            field=wagtail.fields.StreamField([('topic', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('musical_elements', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('element_title', wagtail.blocks.CharBlock()), ('content', wagtail.blocks.StreamBlock([('rich_text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'li', 'hr', 'link', 'document_link'])), ('image', wagtail.blocks.StructBlock([('image_file', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(help_text='Title for the image', required=False)), ('caption', wagtail.blocks.CharBlock(help_text='Caption for the image', required=False))])), ('video', wagtail.blocks.StructBlock([('url', wagtail.blocks.URLBlock()), ('description', wagtail.blocks.CharBlock(required=False))]))], icon='cogs'))])))]))]),
        ),
        migrations.AlterField(
            model_name='eartraininglevelpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock()), ('image', wagtail.blocks.StructBlock([('image_file', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(help_text='Title for the image', required=False)), ('caption', wagtail.blocks.CharBlock(help_text='Caption for the image', required=False))]))]),
        ),
        migrations.AlterField(
            model_name='improvisationcombinationpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock(template='main/blocks/table_block.html')), ('image', wagtail.blocks.StructBlock([('image_file', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(help_text='Title for the image', required=False)), ('caption', wagtail.blocks.CharBlock(help_text='Caption for the image', required=False))]))]),
        ),
        migrations.AlterField(
            model_name='improvisationtypepage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock()), ('image', wagtail.blocks.StructBlock([('image_file', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(help_text='Title for the image', required=False)), ('caption', wagtail.blocks.CharBlock(help_text='Caption for the image', required=False))]))]),
        ),
    ]
