# Generated by Django 2.2.14 on 2020-08-14 17:27

from django.db import migrations
import re


def update_et_titles(apps, schema_editor):
    """Updates Ear Training Element Pages

    Renames page titles to remove leading 'Something with ', where 'Something'
    is one or more words.
    """
    EarTrainingElementPage = apps.get_model('main', 'EarTrainingElementPage')
    for page in EarTrainingElementPage.objects.all():
        page.title = re.sub(r'^((\w+\s)+with\s)(\w+)', r'\3', page.title)
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200728_1326'),
    ]

    operations = [
        migrations.RunPython(
            update_et_titles
        )
    ]
