# Generated by Django 4.2.30 on 2026-08-13 19:05

from django.db import migrations
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
import wagtail.images.blocks


STREAMFIELD_MODELS = [
    'basicpage',
    'eartrainingelementpage',
    'eartraininglevelpage',
    'improvisationcombinationpage',
    'improvisationtypepage',
]


def alter_body_column_type(apps, schema_editor, column_type):
    """Force the ``body`` columns to ``column_type`` on PostgreSQL.

    These StreamFields gained ``use_json_field=True`` without a matching
    migration, and Wagtail 5.0's StreamField reports ``JSONField`` as its
    internal type whether or not that flag is set. Django therefore sees no
    column change to make, so databases migrated before the flag was added
    keep their original ``text`` columns while a freshly built database gets
    ``jsonb``. The ``text`` version breaks JSON lookups with
    ``operator does not exist: text @> jsonb``, so convert explicitly.

    SQLite (used by the Cypress integrationserver) stores JSONField as text
    either way, so there is nothing to do there.
    """
    if schema_editor.connection.vendor != 'postgresql':
        return

    for model_name in STREAMFIELD_MODELS:
        table = apps.get_model('main', model_name)._meta.db_table
        schema_editor.execute(
            'ALTER TABLE {table} ALTER COLUMN {column} TYPE {type} '
            'USING {column}::{type}'.format(
                table=schema_editor.quote_name(table),
                column=schema_editor.quote_name('body'),
                type=column_type,
            )
        )


def body_to_jsonb(apps, schema_editor):
    alter_body_column_type(apps, schema_editor, 'jsonb')


def body_to_text(apps, schema_editor):
    alter_body_column_type(apps, schema_editor, 'text')


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201028_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed'])), ('image', wagtail.blocks.StructBlock([('image_file', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(help_text='Title for the image', required=False)), ('caption', wagtail.blocks.CharBlock(help_text='Caption for the image', required=False))])), ('video', wagtail.blocks.StructBlock([('url', wagtail.blocks.URLBlock()), ('description', wagtail.blocks.CharBlock(required=False))], required=False))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='eartrainingelementpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'hr', 'link', 'document_link'])), ('accessible_text', wagtail.blocks.StructBlock([('visible_text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document_link'], icon='pilcrow', label='Visible text')), ('screen_reader_text', wagtail.blocks.RichTextBlock(features=['ol', 'ul', 'link', 'document_link'], icon='no-view', label='Screen reader text'))])), ('topic', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('musical_elements', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('element_title', wagtail.blocks.CharBlock(required=False)), ('content', wagtail.blocks.StreamBlock([('rich_text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document_link'], required=False)), ('accessible_text', wagtail.blocks.StructBlock([('visible_text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document_link'], icon='pilcrow', label='Visible text')), ('screen_reader_text', wagtail.blocks.RichTextBlock(features=['ol', 'ul', 'link', 'document_link'], icon='no-view', label='Screen reader text'))], required=False)), ('sr_only_text', wagtail.blocks.TextBlock(icon='no-view', label='SR text', required=False, template='main/blocks/screen_reader_block.html')), ('image', wagtail.blocks.StructBlock([('image_file', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(help_text='Title for the image', required=False)), ('caption', wagtail.blocks.CharBlock(help_text='Caption for the image', required=False))], required=False)), ('video', wagtail.blocks.StructBlock([('url', wagtail.blocks.URLBlock()), ('description', wagtail.blocks.CharBlock(required=False))], required=False)), ('table', wagtail.contrib.table_block.blocks.TableBlock(template='main/blocks/table_block.html'))], icon='cogs', required=False))]), required=False))])), ('video', wagtail.blocks.StructBlock([('url', wagtail.blocks.URLBlock()), ('description', wagtail.blocks.CharBlock(required=False))], required=False))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='eartraininglevelpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'hr', 'link', 'document-link', 'image', 'embed'])), ('image', wagtail.blocks.StructBlock([('image_file', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(help_text='Title for the image', required=False)), ('caption', wagtail.blocks.CharBlock(help_text='Caption for the image', required=False))])), ('video', wagtail.blocks.StructBlock([('url', wagtail.blocks.URLBlock()), ('description', wagtail.blocks.CharBlock(required=False))], required=False))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='improvisationcombinationpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'hr', 'link', 'document-link', 'image', 'embed'])), ('table', wagtail.contrib.table_block.blocks.TableBlock(template='main/blocks/table_block.html')), ('image', wagtail.blocks.StructBlock([('image_file', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(help_text='Title for the image', required=False)), ('caption', wagtail.blocks.CharBlock(help_text='Caption for the image', required=False))])), ('video', wagtail.blocks.StructBlock([('url', wagtail.blocks.URLBlock()), ('description', wagtail.blocks.CharBlock(required=False))], required=False))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='improvisationtypepage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'hr', 'link', 'document-link', 'image', 'embed'])), ('image', wagtail.blocks.StructBlock([('image_file', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(help_text='Title for the image', required=False)), ('caption', wagtail.blocks.CharBlock(help_text='Caption for the image', required=False))])), ('video', wagtail.blocks.StructBlock([('url', wagtail.blocks.URLBlock()), ('description', wagtail.blocks.CharBlock(required=False))], required=False))], use_json_field=True),
        ),
        migrations.RunPython(body_to_jsonb, body_to_text),
    ]
